import type { Metadata } from 'next';
import './globals.css';

import { pretandard } from '@/assets/fonts';

export const metadata: Metadata = {
  title: 'Hexa.Loa',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={'en'}>
      <body className={pretandard.className}>
        {children}
      </body>
    </html>
  );
}
